import {
  LayoutDashboard,
  Globe,
  Users,
  CalendarCheck,
  KeyRound,
  Mails,
  HandCoins,
  ScrollText,
  Tags,
  Layers,
  Megaphone,
  Fingerprint,
  Clock,
  ReceiptText,
  Receipt,
  CalendarOff,
  Briefcase,
  FolderKanban,
  Building2,
  UserCog,
  DollarSign,
  Shield,
  Circle,
  type LucideIcon,
} from 'lucide-react';

export const iconMap: Record<string, LucideIcon> = {
  LayoutDashboard,
  Globe,
  Users,
  CalendarCheck,
  KeyRound,
  Mails,
  HandCoins,
  ScrollText,
  Tags,
  Layers,
  Megaphone,
  Fingerprint,
  Clock,
  ReceiptText,
  Receipt,
  CalendarOff,
  Briefcase,
  FolderKanban,
  Building2,
  UserCog,
  DollarSign,
  Shield,
};

export const getIconComponent = (iconName: string | null): LucideIcon => {
  if (!iconName) return Circle;
  return iconMap[iconName] || Circle;
};
