import { useCallback, useMemo, useState } from 'react';
import { PenTool, Plus } from 'lucide-react';

import {
  Button,
  ListControls,
  NoDataFound,
  PageHeader,
  PermissionGate,
  WarningModal,
} from '../../components/common';
import { SignatoryCard } from '../../features/letter-management/components/SignatoryCard/SignatoryCard';
import { SignatoryFormModal } from '../../features/letter-management/components/SignatoryFormModal/SignatoryFormModal';
import {
  useArchiveSignatory,
  useSetDefaultSignatory,
  useSignatories,
} from '../../features/letter-management/hooks/useSignatories';
import { useDebounce } from '../../hooks/useDebounce';
import { useModuleAccess } from '../../hooks/useModuleAccess';
import { ModuleCode, ActionCode } from '../../enum/modules';

import styles from './SignatoriesPage.module.scss';

import type { Signatory } from '../../features/letter-management/types/letterTypes';

const SignatoriesPage = () => {
  const [searchQuery, setSearchQuery] = useState('');
  const [isFormOpen, setIsFormOpen] = useState(false);
  const [editingSignatory, setEditingSignatory] = useState<Signatory | null>(null);
  const [showArchiveModal, setShowArchiveModal] = useState(false);
  const [selectedSignatory, setSelectedSignatory] = useState<Signatory | null>(null);

  const { hasCreateAccess, hasEditAccess, hasDeleteAccess, hasActivateAccess } = useModuleAccess(
    ModuleCode.LETTER_SIGNATORIES,
  );

  const debouncedSearchQuery = useDebounce(searchQuery, 300);

  const { data: response, isLoading } = useSignatories(debouncedSearchQuery || undefined);
  const { mutate: setDefaultSignatory } = useSetDefaultSignatory();
  const { mutate: archiveSignatory, isPending: isArchiving } = useArchiveSignatory();

  const signatoryList = useMemo(() => response?.data || [], [response]);

  const handleAddSignatory = useCallback(() => {
    setEditingSignatory(null);
    setIsFormOpen(true);
  }, []);

  const handleEditSignatory = useCallback((signatory: Signatory) => {
    setEditingSignatory(signatory);
    setIsFormOpen(true);
  }, []);

  const handleSetDefault = useCallback(
    (signatory: Signatory) => {
      setDefaultSignatory(signatory.id);
    },
    [setDefaultSignatory],
  );

  const handleArchiveClick = useCallback((signatory: Signatory) => {
    setSelectedSignatory(signatory);
    setShowArchiveModal(true);
  }, []);

  const handleArchive = useCallback(() => {
    if (selectedSignatory) {
      archiveSignatory(selectedSignatory.id, {
        onSuccess: () => setShowArchiveModal(false),
      });
    }
  }, [selectedSignatory, archiveSignatory]);

  const renderContent = () => {
    if (signatoryList.length === 0) {
      return (
        <NoDataFound
          title="No Signatories Found"
          description="We couldn't find any signatory matching your current search. Try adjusting your search term."
        />
      );
    }

    return (
      <div className={styles.grid}>
        {signatoryList.map((signatory) => (
          <SignatoryCard
            key={signatory.id}
            signatory={signatory}
            onEdit={hasEditAccess ? () => handleEditSignatory(signatory) : undefined}
            onSetDefault={hasActivateAccess ? () => handleSetDefault(signatory) : undefined}
            onArchive={hasDeleteAccess ? () => handleArchiveClick(signatory) : undefined}
          />
        ))}
      </div>
    );
  };

  if (!isLoading && signatoryList.length === 0 && !debouncedSearchQuery) {
    return (
      <>
        <NoDataFound
          title="No Signatories Added Yet"
          description="Add a signatory to attach their name, designation and signature to generated letters."
          buttonText={hasCreateAccess ? 'Add Signatory' : undefined}
          onButtonClick={hasCreateAccess ? handleAddSignatory : undefined}
          showButtonIcon={hasCreateAccess}
        />
        <SignatoryFormModal
          key={isFormOpen ? editingSignatory?.id || 'new' : 'closed'}
          isOpen={isFormOpen}
          onClose={() => {
            setIsFormOpen(false);
            setEditingSignatory(null);
          }}
          signatory={editingSignatory}
        />
      </>
    );
  }

  return (
    <div className={`${styles.container} ${isLoading ? styles.loading : ''}`}>
      <PageHeader
        title="Signatories"
        titleExtra={
          <span className={styles.pageIcon}>
            <PenTool size={20} />
          </span>
        }
        subtitle="Manage the signatories available for letters generated by your organization."
        actions={
          <PermissionGate module={ModuleCode.LETTER_SIGNATORIES} action={ActionCode.CREATE}>
            <Button variant="primary" onClick={handleAddSignatory}>
              <Plus size={16} />
              Add Signatory
            </Button>
          </PermissionGate>
        }
      />

      <ListControls
        showSearch
        showFilters={false}
        showSort={false}
        showMultiSelect={false}
        showViewSwitcher={false}
        searchPlaceholder="Search signatories..."
        searchQuery={searchQuery}
        onSearchChange={setSearchQuery}
      />

      {renderContent()}

      <WarningModal
        isOpen={showArchiveModal}
        onClose={() => setShowArchiveModal(false)}
        title="Archive Signatory"
        description={`Are you sure you want to archive "${selectedSignatory?.name}"? ${
          selectedSignatory?.is_default
            ? 'This is currently the default signatory — set another signatory as default before it can be archived.'
            : 'This action cannot be undone.'
        }`}
        actionLabel="Archive"
        actionVariant="danger"
        onAction={handleArchive}
        isActionLoading={isArchiving}
      />

      <SignatoryFormModal
        key={isFormOpen ? editingSignatory?.id || 'new' : 'closed'}
        isOpen={isFormOpen}
        onClose={() => {
          setIsFormOpen(false);
          setEditingSignatory(null);
        }}
        signatory={editingSignatory}
      />
    </div>
  );
};

export default SignatoriesPage;
